export default en = {
  discover: 'Discover',
  favourites: 'Favourites',
  openNow: 'Open now',
  places: 'Places',
  nearby: 'Nearby',
  myProfile: 'My Profile',
  price: 'Price',
  name: 'Name',
  challenges: 'Challenges',
  profile: 'Profile',
  statistics: 'Statistics',
  badges: 'Badges',
  me: 'Me',
  menu: 'Menu',
  back: 'Back',
  newbie: 'Newbie',
  master: 'Master',
  hero: 'Hero',
  giant: 'Giant',
  summer: 'Summar',
  autumn: 'Autumn',
};
