export default sv = {
  discover: 'Upptäck',
  favourites: 'Favoriter',
  openNow: 'Öppet nu',
  places: 'Ställen',
  nearby: 'Nära dig',
  myProfile: 'Min Profil',
  price: 'Pris',
  name: 'Namn',
  challenges: 'Utmaningar',
  profile: 'Profil',
  statistics: 'Statistik',
  badges: 'Utmärkelser',
  me: 'Jag',
  menu: 'Meny',
  back: 'Tillbaka',
  newbie: 'Nybörjare',
  master: 'Mästare',
  hero: 'Hjälte',
  giant: 'Jätten',
  summer: 'Sommar',
  autumn: 'Höst',
};
